import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import ToasterProvider from "./providers/ToasterProvider";
import SignalRProvider from "./providers/SignalRProvider";
import { ReactNode } from "react";
import { User } from "next-auth";

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  user: User;
};

export default async function RootLayout({ children, user }: Props) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className="container mx-auto px-5 pt-10">
          <SignalRProvider user={user}>{children}</SignalRProvider>
        </main>
      </body>
    </html>
  );
}
